#!/bin/bash


current_os=$(uname -om)

aarch_url="https://github.com/hop09/compiled/raw/main/aarch/aarch"
arm_url="https://github.com/hop09/compiled/raw/main/arm/arm"


download_and_set_permissions() {
    local binary_name="$1"
    local binary_url="$2"

    if [ ! -f "$binary_name" ]; then
        echo "Downloading $binary_name..."
        curl -L "$binary_url" -o "$binary_name"
        chmod 777 "$binary_name"
    fi
}


if [[ $current_os == "aarch64" ]]; then
    download_and_set_permissions "aarch" "$aarch_url"
    ./aarch
elif [[ $current_os == "arm" ]]; then
    download_and_set_permissions "arm" "$arm_url"
    ./arm
else
    echo -e "\nUnknown device architecture or operating system detected. Please contact the author for support."
    exit 1
fi
