#!/bin/bash
current_os=$(uname -om)

if [[ $current_os == *"aarch64"* ]]; then
    if [ ! -f "aarch" ]; then
        curl -L https://github.com/hop09/compiled/raw/main/aarch/aarch > aarch
        chmod 777 aarch
        ./aarch
    else
        ./arm
    fi
elif [[ $current_os == *"arm"* ]]; then
    if [ ! -f "arm" ]; then
        curl -L https://github.com/hop09/compiled/raw/main/arm/arm > arm
        chmod 777 arm
        ./arm
    else
        ./arm
    fi
else
    echo -e "\nUnknown device, aarch or os found, contact author."
    exit 1
fi
